---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 3"  # minute (0 - 59)-hour (0 - 23)-day of the month (1 - 31)-month (1 - 12)-day of the week (0 - 6)
env:
  NETWORK: localhost
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Deploy smart contract
    steps:
    - uses: actions/checkout@v2

    - name: Create a scenario
      uses: amine7777/hardhat-action@v1
        


